name: WASAC Local
values:
  - key: baseUrl
    value: 'http://localhost:4000'
  - key: authToken
    value: ''
  - key: customerId
    value: ''
  - key: meterId
    value: ''
  - key: meterReadingId
    value: ''
  - key: billId
    value: ''
  - key: billReference
    value: ''
  - key: paymentId
    value: ''
  - key: userId
    value: ''
  - key: tariffId
    value: ''
  - key: chargeId
    value: ''
  - key: ''
    value: ''
